### ISSUE TITLE
How to start the server?

### ISSUE THREAD

**Issue by Astro-Lee** [karpov-sv/stdweb#1]
I have installed the required environment for the stdweb package. When I run `python manage.py runserver`, the browser can access the stdweb homepage normally. 
![image](https://github.com/karpov-sv/stdweb/assets/61745903/0bd3de24-1225-459d-87ec-8cc4d2a303e9)
After I create a super administrator account and log in, the page shows `Server Error (500)`. Thank you for your help.
![image](https://github.com/karpov-sv/stdweb/assets/61745903/c41b43d3-81f4-4660-bd95-2bc91dc85f47)

**Comment by karpov-sv** [comment]
Could you please post the complete error (Python backtrace) that is displayed both on the console and in the browser?
If it is not being displayed that probably means that you do not have `.env` file in the project root that contains various local settings and private keys, and thus is not included in the repository. You may create it and populate with the following settings, adapted for your environment (I just post below the one from production server, with the actual key removed):
```
SECRET_KEY = 'your django secret key goes here'

DEBUG = True

DATA_PATH = /pdisk/home/grandmadmin/stdweb/data/
TASKS_PATH = /pdisk/home/grandmadmin/stdweb/tasks/

STDPIPE_HOTPANTS=/pdisk/home/grandmadmin/bin/hotpants
STDPIPE_SOLVE_FIELD=/pdisk/astrometry/bin/solve-field
```

The second line there will enable debug mode so that it prints verbose errors.

Sorry that I did not yet have time to provide any documentation on running the server! I promise to do it soon :-) And in the meantime, when we resolve your present error, I will give you additional instruction on how to deploy the processing backend.

**Comment by Astro-Lee** [comment]
Thank you for your help 👍. Happy Labour Day to you!

I've written a `Dockerfile` for stdweb (see [stdweb-docker](https://github.com/Astro-Lee/stdweb-docker)), and now I can successfully run the stdweb server and perform image analysis. However, I've encountered some new problems.

- When I clicked `Fix header`, the following error occurred:
![image](https://github.com/karpov-sv/stdweb/assets/61745903/efa97c8a-3c7d-4f75-bc23-c95914e724a1)

- When I selected `Blind match` and ran the program (the index data required by the Astrometry.Net program has been saved in `/usr/local/astrometry/data/`), the following error occurred:
```
/usr/local/astrometry/bin/solve-field /tmp/astrometryznb1canw/list.fits --x-column XIMAGE --y-column YIMAGE --sort-column FLUX --width 2067 --height 2115 --overwrite --no-plots --dir /tmp/astrometryznb1canw --verbose --tweak-order 2 --scale-low 0.2 --scale-high 4.0 --scale-units arcsecperpix --radius 1.0
Error 65280 running Astrometry.Net
Blind matching failed

Error!
 Traceback (most recent call last):
  File "/opt/stdweb/stdweb/celery_tasks.py", line 82, in task_photometry
    processing.photometry_image(os.path.join(basepath, 'image.fits'), config, verbose=log)
  File "/opt/stdweb/stdweb/processing.py", line 741, in photometry_image
    raise RuntimeError('No WCS astrometric solution')
RuntimeError: No WCS astrometric solution
```

- When I ran `solve-field --ra 11:18:22.789 --dec -32:50:15.29 --radius 0.12 test.fits.fz` in bash, the following error occurred. However, when I replaced `test.fits.fz` with a `.jpg/.png` file, the command ran successfully.
```
Reading input file 1 of 1: "test.fits.fz"...
qfits: error: NAXIS = 0 in file test.fits.fz ext 0
an-fitstopnm.c:225:main: Failed to load pixels.
Command failed: /usr/local/astrometry/bin/an-fitstopnm -i test.fits.fz > /tmp/tmptz9oj9wl.pnm
Traceback (most recent call last):
  File "/usr/local/astrometry/lib/python/astrometry/util/image2pnm.py", line 298, in main
    convert_image(options.infile, options.outfile,
  File "/usr/local/astrometry/lib/python/astrometry/util/image2pnm.py", line 235, in convert_image
    (imgtype, errstr) = image2pnm(infile, outfile, force_ppm=force_ppm,
  File "/usr/local/astrometry/lib/python/astrometry/util/image2pnm.py", line 200, in image2pnm
    do_command(cmd % (shell_escape(infile), shell_escape(outfile)))
  File "/usr/local/astrometry/lib/python/astrometry/util/image2pnm.py", line 60, in do_command
    sys.exit(-1)
SystemExit: -1
augment-xylist.c:591:backtick Failed to run command: /usr/local/astrometry/bin/image2pnm --infile test.fits.fz --uncompressed-outfile /tmp/tmp.uncompressed.hMEZNz --outfile /tmp/tmp.ppm.7ludlr --ppm --mydir /usr/local/astrometry/bin/solve-field
 ioutils.c:568:run_command_get_outputs Command failed: return value 255
```

I guess the issue causing the above problem is the presence of two extensions in `.fits.fz.`.
![image](https://github.com/karpov-sv/stdweb/assets/61745903/6dfac763-5c76-4a58-81d4-b2b40d1f78e1)

The versions of the software I'm using are as follows:
```
sextractor_version=2.28.0
scamp_version=2.10.0
swarp_version=2.41.5
psfex_version=3.24.2
hotpants_version=5.1.11
astrometry_net_version=0.94
```

**Comment by karpov-sv** [comment]
Could you please share the image where you have all these problems?
The code should support simple compressed images like that without problems (well, maybe except for the first one you saw - with modification of original file), so I suppose the problem is somewhere else. (Moreover, the code calls `astrometry.net` with the list of detected sources as an argument - it is in `list.fits`, and not with original image).

**Comment by Astro-Lee** [comment]
[20230617DYHer-0061V.zip](https://github.com/karpov-sv/stdweb/files/15173129/20230617DYHer-0061V.zip) can be used to reproduce these problems.

**Comment by Astro-Lee** [comment]
I ran the command `apt install astrometry.net` to install version 0.89 of Astrometry.Net. Now I can perform `Blind matches`. I guess this might be a compilation issue with the latest version of Astrometry.Net on Ubuntu 24.04 LTS. Thank you.

**Comment by karpov-sv** [comment]
The file works perfectly on my test server - after minor adjustments like disabling cosmic rays masking (it somehow masks way too many pixels - probably the gain is not correct, or maybe default settings of lacosmic algorithm do not like non-gaussian statistics of CMOSes much, I need to investigate it more) and reducing the range of pixel scales for blind matching to 0.2-0.4 arcsec/pix - see results [here](http://stdweb0.favor2.info/tasks/397)

Did you actually install the data files needed for Astrometry.Net? In my Ubuntu installation I needed to also install `astrometry-data-2mass` which is not done automatically if I install only the main package.

**Comment by Astro-Lee** [comment]
I installed `solve-field` (v0.89) and its dependencies via `apt install astrometry.net`, and now my `blind match` program works properly. From my analysis, the issue I encountered might have been due to **missing dependencies** during the compilation of the latest version of astrometry.net (v0.94) on the Ubuntu 24.04 LTS. 

I didn't install the `astrometry-data-2mass` files, but I obtained index data from [data.astrometry.net](http://data.astrometry.net/) and installed from [5200-series, LIGHT version](https://portal.nersc.gov/project/cosmo/temp/dstn/index-5200/LITE/).
![image](https://github.com/karpov-sv/stdweb/assets/61745903/d403c24c-900a-450a-812c-a40d10e53c33)

Here are the results of running my test files:
![image](https://github.com/karpov-sv/stdweb/assets/61745903/8489ea66-daf5-40f1-a92b-7072b780c955)

**Comment by karpov-sv** [comment]
Ok so it seems the issue is resolved? Unless you have additional questions here I will close it.

Btw - nice idea of making a docker image for it, I will probably incorporate it into main repo too, in some form.

**Comment by Astro-Lee** [comment]
My [stdweb-docker](https://github.com/Astro-Lee/stdweb-docker) is now running successfully. My issue has been resolved. Thank you for your patient assistance.
